# Generated by Django 5.0.1 on 2024-01-31 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feeding',
        ),
    ]
